### PR TITLE
LPS-70431 Avoid rendering when ddmFormFieldValue has null Value

### PR DESCRIPTION
**Pull request by SpencerWoo**
Resent : https://github.com/rafaprax/liferay-portal/pull/164

"marcellustavares : please create a unit test for this bug. Thanks"

### CODE REVIEW

**Comment by SpencerWoo** [comment]
Hi @rafaprax 

I've never done a PR to a sub repo before so let me know if I should do the PR a different way or if you need anything from me.  Thanks!

**Comment by SpencerWoo** [comment]
@rafaprax any progress on this?

**Comment by rafaprax** [comment]
@SpencerWoo I will take a look on this tomorrow(I need to finish some stuff before). Could you wait until there? Thx

**Comment by SpencerWoo** [comment]
@rafaprax Thanks for the reply and the timeline!  Understand, and will do.

**Comment by rafaprax** [comment]
I reopened the https://github.com/rafaprax/liferay-portal/pull/164 pr

**Pull request closed without merging**
